### ISSUE TITLE
Is tibble a required dependency?

### ISSUE THREAD

**Issue by sda030** [ThinkR-open/lightparser#5]
Hi Sebastien, neat package. I just wonder whether the tibble-import is strictly required, or whether it could be optional? One always have to consider downstream reuse, and avoid dependencies whenever needed. I very much like and use tibble in my daily routines, but try to avoid it in packages. You also do not rely on dplyr or other packages that would have imported it. Just a thought before I consider replacing my own internal (complex) machinery with yours.

Also, would you consider the package stable, no foreseeable breaking changes?

Best, Stephan

**Comment by statnmap** [comment]
Hi Stephan,
I understand.  
I used 'tibble' to benefit from its specific properties, like keeping the rectangular format when you select only one column, or being able to easily deal with list-columns.  
I thought about removing it to reduce dependencies, but that would mean to deal with all side effects of dataframes.  
Also, I think a lot of users already have 'tibble' installed, so I assumed that would not be a big problem.

For now, I do not see breaking changes coming, I think this package will keep it simple, as long as it serves the needs of 'fusen'.

**Comment by sda030** [comment]
I think you have pretty good arguments for using tibble. I also will likely end up depending on tibble myself. :)
